version: 1

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: portainer-cli
    main: ./cmd/portainer-cli
    binary: portainer-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.Commit}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: portainer-cli
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: rob
    name: portainer-cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Portainer CLI {{.Version}}
    
    Release notes for version {{.Version}}.
  footer: |
    ## Installation
    
    Download the appropriate binary for your platform from the assets below.
    
    ### Linux/macOS
    ```bash
    # Extract and install
    tar -xzf portainer-cli_{{.Version}}_<OS>_<ARCH>.tar.gz
    sudo mv portainer-cli /usr/local/bin/
    ```
    
    ### Windows
    Extract the zip file and add the binary to your PATH.
